name: CI_DEPLOY

on:
  push:
    branches:
      - 'main'

env:
   SERVER_HOST: 84.23.54.189
   SERVER_USER: ubuntu
   SERVER_PATH: /home/ubuntu

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4 

      - name: Setup go
        uses: actions/setup-go@v4
        with: 
          go-version: '1.21'
          
      - name: Build binary
        run: |
          go build -o "cmd/films" "cmd/films/main.go" && \
          go build -o "cmd/comments" "cmd/comments/main.go" && \
          go build -o "cmd/authorization" "cmd/authorization/main.go"

      - name: Copy files to server
        run: scp cmd/films cmd/comments cmd/authorization $SERVER_USER@$SERVER_HOST:$SERVER_PATH

      - name: Dry run rsync
        run: rsync --archive --compress --dry-run . ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:${{ env.SERVER_PATH }}
