name: CI_DEPLOY

on:
  push:
    branches:
      - 'main'

env:
   SERVER_HOST: 84.23.54.189
   SERVER_USER: ubuntu
   SERVER_PATH: /home/ubuntu

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4 

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
           key: "${{ secrets.DEPLOY_KEY }}"
           known_hosts: "placeholder"
      
      - name: Generate auth hosts
        run: ssh-keyscan -H ${{ env.SERVER_HOST }} >> ~/.ssh/known_hosts
        
      - name: Setup go
        uses: actions/setup-go@v4
        with: 
          go-version: '1.21'
          
      - name: Build binary
        run: |
          go build -o "cmd/films" "cmd/films/main.go" && \
          go build -o "cmd/comments" "cmd/comments/main.go" && \
          go build -o "cmd/authorization" "cmd/authorization/main.go"


      - run: rsync --archive --compress --progress . ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}
