name: CI_DEPLOY

on:
  push:
    branches:
      - 'main'

env:
   SERVER_HOST: your_server_ip
   SERVER_USER: your_username
   SERVER_PATH: /path/to/destination/directory

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4 

      - name: Setup go
        uses: actions/setup-go@v4
        with: 
          go-version: '1.21'
          
      - name: Build binary
        run: |
          go build -o "cmd/films" "cmd/films/main.go" && \
          go build -o "cmd/comments" "cmd/comments/main.go" && \
          go build -o "cmd/authorization" "cmd/authorization/main.go"

      - name: Update known hosts
        run: ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts

      - name: Copy files to server
        run: scp cmd/films cmd/comments cmd/authorization $SERVER_USER@$SERVER_HOST:$SERVER_PATH
