name: CI_DEPLOY

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v4
        with: 
          go-version: '1.21'

      - name: Build binary
        run: |
          go build -o "cmd/films" "cmd/films/main.go" && \
          go build -o "cmd/comments" "cmd/comments/main.go" && \
          go build -o "cmd/authorization" "cmd/authorization/main.go"
      - name: Tar files
          run: tar -czvf /tmp/LechzzIHPW.tar.gz cmd/ configs/
      - name: Copy file
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "cmd, configs"
          target: /home/ubuntu/

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            systemctl restart movie_hub
